# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a87b81e8538e46761437b1bb62c949cb7cafa6ce06c6189710351380237b4a29a11b2a1ed973ad8bffcc9d68357b2f8dfcd88eebdd9a9df95d6758d755c178a9

test:
  secret_key_base: 1f7a6e2ad3e5704f10bf65b426eab661fdaa0cb800e36e06192550f9368154ab55a788816ffbc3eebf5fd6156d2526e60e6693f2eae60232bc7d90ccecd2ac3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
